version: '3'

services:
  database:
    image: 'mysql:5.7'

    ports:
      - '3306:3306'

    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

    env_file:
      - .env

    volumes:
      - ./db-data/:/var/lib/mysql
