name: API Deploy


on:
  push:
    branches: [ "master" ]


jobs:
  build:
  
    runs-on: self-hosted

    strategy:
      matrix:
        configuration: [Release]


    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Build and push Docker image
    - name: Build and Push Docker Image
      env:
        ENV: ${{ secrets.ENV }}
      run: |
        echo "$ENV" | base64 -d > .env
        docker build -t quizap/api .

    # Ejecute post file
    - name: Ejecute Server File
      run: "~/api.sh"